name: travel-calculator
services:
- name: web
  github:
    branch: main
    deploy_on_push: true
    repo: your-github-username/travel-calculator
  health_check:
    http_path: /health
  http_port: 5000
  instance_count: 1
  instance_size_slug: basic-xxs
  run_command: gunicorn --bind 0.0.0.0:5000 app:app
  envs:
  - key: FLASK_APP
    value: app.py
  - key: FLASK_ENV
    value: production
  - key: SECRET_KEY
    scope: RUN_TIME
    type: SECRET
  - key: SMTP_USERNAME
    scope: RUN_TIME
    type: SECRET
  - key: SMTP_PASSWORD
    scope: RUN_TIME
    type: SECRET
  - key: TWILIO_ACCOUNT_SID
    scope: RUN_TIME
    type: SECRET
  - key: TWILIO_AUTH_TOKEN
    scope: RUN_TIME
    type: SECRET
  - key: TWILIO_PHONE_NUMBER
    scope: RUN_TIME
    type: SECRET 